name: AFKPlugin
main: de.kallifabio.afk.main.Main
version: 1.3
author: kallifabio
description: A Simple AFK plugin

commands:
  afk: 
    description: MainCommand
    usage: 
  unafk: 
    description: SubCommand
    usage: